language: java
jdk:
  - oraclejdk8
dist: trusty
install:
  - mvn clean
script:
  - mvn verify -P travis
#  - mvn clean install sonar:sonar
after_success:
#  - codecov
  - mvn clean test jacoco:report coveralls:report
#cache:
#    directories:
#        - $HOME/.m2
#notifications:
#  email:
#    recipients:
#      - duo.liu@kikatech.com
#    on_success: change
#    on_failure: always
#  slack:
#    rooms:
#      - xinmei:o1s98YYkax9sjJmUBapVzyll
#    on_success: change
#    on_failure: always
